// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVESsQKo-QO7DFOODvxltMjumHKV_384',
    appId: '1:1054024451351:web:61cb3a264767bb354e2352',
    messagingSenderId: '1054024451351',
    projectId: 'eng-capstone',
    authDomain: 'eng-capstone.firebaseapp.com',
    storageBucket: 'eng-capstone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHLy43K7WIzQT-awSyXvpO1pMQ2x9gE4',
    appId: '1:1054024451351:android:a3af6b48bc7e60564e2352',
    messagingSenderId: '1054024451351',
    projectId: 'eng-capstone',
    storageBucket: 'eng-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwoibznM77-Bu4dskEBIABEznb0_YX9pw',
    appId: '1:1054024451351:ios:8e42f81cc03813c34e2352',
    messagingSenderId: '1054024451351',
    projectId: 'eng-capstone',
    storageBucket: 'eng-capstone.appspot.com',
    iosBundleId: 'com.capstone.eeCapstoneProject',
  );
}
